language: python
sudo: false
bundler_args: --retry 8

python:
  - 2.7

before_install:
  - pip install "setuptools<45"
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - python setup.py test -q
