

def includeme(config):
    config.include('.tinymce')
    config.include('.actions')
    config.include('.auth')
    config.include('.base')
    config.include('.contents')
    config.include('.customize_addable_content')
    config.include('.cut_copy_paste')
    config.include('.file')
    config.include('.flash_messages')
    config.include('.groups')
    config.include('.ie_compat_header')
    config.include('.image')
    config.include('.initial_setup')
    config.include('.languages')
    config.include('.link')
    config.include('.listing')
    config.include('.permissions')
    config.include('.portlets')
    config.include('.revisions')
    config.include('.roles_log')
    config.include('.search')
    config.include('.selected_content')
    config.include('.site_settings')
    config.include('.user')
    config.include('.users')
    config.include('.view_settings')
    config.include('.workflow')
    if config.registry.settings.get('arche.use_exception_views', False):
        config.include('.exceptions')
